Portfolio: finish mobile version
momotsow/microverse-portfolio pull request #2
Opened 2022-09-22 11:34 UTC by momotsow

For this Portfolio project I have added 2 sections as per the requirement namely:

- Work Section
- About Myself Section

I have chosen Figma Template 5 for this exercise.

2022-09-22 11:49 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @momotsow, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Great UI design following the Figma template almost perfectly. ✔️ ✔️ ✔️
 - No linter errors. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 11:49 UTC, leonardodiasb commented on index.html
> +        <h1 class="tittle t2">Projects</h1>
- [ ] Your project already has a main title with the `<h1>` tag. Please follow the headings hierarchy and use a proper `<hx>` tag for this section title. [Read this article for more information](https://www.reliablesoft.net/h1-tag/)

2022-09-22 11:49 UTC, leonardodiasb commented on styles.css
> +  }
- [ ] This title does not have the same font-family, font-size, and color as the Figma template. Please add these attributes to make it look more like the template.

2022-09-22 11:49 UTC, leonardodiasb commented on index.html
> +        <h1 class="tittle">About</h1>
- [ ] Your project already has a main title with the `<h1>` tag. Please follow the headings hierarchy and use a proper `<hx>` tag for this section title. [Read this article for more information](https://www.reliablesoft.net/h1-tag/)
 - [ ] This title does not have the same font-family, font-size, and color as the Figma template. Please add these attributes to make it look more like the template.

2022-09-22 11:49 UTC, leonardodiasb commented on index.html
> +        </div>
- [ ] This is a list of technology categories, and an `<ul>` tag with a `<li>` tag for each category would be better appropriate in this situation for semantic reasons. Kindly change the HTML tags.

2022-09-22 16:15 UTC, momotsow commented
Hi @leonardodiasb,

I need clarity on the last review.
In my own understanding of you review- you are saying I should use an unordered list `<ul><li></li></ul>`

I believe that's what I did as I created 4 Articles/cards with an unordered list inside as per the Figma design
![image](https://user-images.githubusercontent.com/41517876/191799196-a970cdd1-b913-4532-8f63-20e04a790249.png)

2022-09-23 05:29 UTC, mgmediaweb commented on index.html
> +        <h1 class="tittle t2">Projects</h1>
Good job following the advice of the previous reviewer

2022-09-23 05:35 UTC, mgmediaweb requested changes
Hi @momotsow , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost4](https://user-images.githubusercontent.com/41912912/191897653-6bf35c5f-488d-4195-830e-a9feb5f4f82e.gif)

 ## Highlights 💯 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️ 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 05:35 UTC, mgmediaweb commented on index.html
> +                <button class="project-link">JavaScript</button>
kindly, I suggest following the advice of the previous reviewer and use UL/LI lists to organize languages

2022-09-23 05:35 UTC, mgmediaweb commented on index.html
> +                <button class="project-link">JavaScript</button>
kindly, I suggest following the advice of the previous reviewer and use UL/LI lists to organize languages

2022-09-23 06:38 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @momotsow  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)


## Highlights :sparkles:

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 06:42 UTC, merged